services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ultimate_race_db
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - ultimate_race_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ultimate_race_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - ultimate_race_network

volumes:
  postgres_data:

networks:
  ultimate_race_network:
    driver: bridge 